# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e28b54259656cb3c246c89f5c7baa3b915f34a2ebfd6eca9942c22919bb26cc992f09ec47225d69d7a4d6b816583cf6e33a2ac6568742ee8fa3ffec67856546d

test:
  secret_key_base: 1b8d7c5c79d37caf8d91629682c499015f70c4909eba3a5af7082ffbe5c74b8fd7e8b80d6e2883bc1e6cec5af895d4aa3435e690ba272e1e03101d98a5ff18d2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
